name = "llm.lean"
version = "0.1.0"
authors = ["Alok Singh <alokbeniwal@gmail.com>", "Govind Pimpale"]

[[lean_lib]]
name = "LinearAlgebra"
src = "LinearAlgebra"

[[lean_lib]]
name = "Llm"
src = "Llm"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "scilean"
git = "https://github.com/lecopivo/scilean.git"
rev = "53f112d"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible.git"
rev = "main"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries.git"
rev = "main"