name = "LlmLean"
defaultTargets = ["LinearAlgebra", "Llm"]

[[lean_lib]]
name = "LinearAlgebra"
srcDir = "lean/LinearAlgebra"

[[lean_lib]]
name = "Llm"
srcDir = "lean/Llm"

[[lean_exe]]
name = "test"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

# v1.4.1 works with toolchain 4.10.0-rc1
# [[require]]
# name = "LeanCopilot"
# git = "https://github.com/lean-dojo/LeanCopilot.git"
# rev = "v1.4.1"
# moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]
